theme: jekyll-theme-minimal

title: Hi there!
description: My name is Dan Wang. I'm a PhD student majored in self-driving car and machine learning. It's nice to meet you.

logo: /img/Avatar_DanWang.jpg
show_downloads: true
google_analytics:
